### ISSUE TITLE
about waveform

### ISSUE THREAD

**Issue by pragyantpradab** [iris-edu/pyweed#122] opened 2021-08-01 13:02 UTC
Does waveform given by PYWEED app have instrument response/pole-zero file removed ? or do  I have to download response file separately for these waveforms ?

**Comment by adam-iris** [comment] 2021-08-02 16:48
Currently the response metadata is not downloaded, but it should be.

**Comment by adam-iris** [comment] 2021-08-02 16:49
Duplicate of #108

**Closed by adam-iris** 2021-08-02 16:49 UTC
